name: MOTD
version: 2.9.1
main: me.jdog.motd.MOTD
depend: [murAPI]
authors: [Muricans]
description: Recreating my old plugin 'MOTD' but for updated versions of Minecraft since it broke.
website: https://commonly.github.io
commands:
  motd:
    permission: motd.admin
    permission-message: No permission.
    usage: /<command> <args>
    description: MOTD admin command.
